# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
#permalink:           pretty

# Setup
title:               Kriti Shrivastwa
tagline:             ''
description:         'Coder | Explorer | Reader | Pythonista'
url:                 
baseurl:             '/'
paginate:            5

# About/contact
author:
  name:              kriti kumari
  url:               https://twitter.com/kriti_k01
  email:             kriti.cs10@gmail.com
